name: osx-release

on:
  workflow_dispatch:
  push:
    branches: [ main, release ]

jobs:
  build-and-lay-out:
    name: Build and lay out macOS payload
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.

    - name: Set up dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.201
    
    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build --configuration=MacRelease
    
    - name: Run macOS unit tests
      run: |
        dotnet test --configuration=MacRelease

    - name: Lay out payload and symbols
      run: |
        src/osx/Installer.Mac/layout.sh --configuration=MacRelease --output=out/osx/payload --symbol-output=out/osx/symbols

    - name: Upload payload
      uses: actions/upload-artifact@v2
      with:
        name: macos-payload
        path: out/osx/payload
    
    - name: Upload symbols
      uses: actions/upload-artifact@v2
      with:
        name: macos-symbols
        path: out/osx/symbols
  
  sign-payload:
    name: Sign macOS payload
    # ESRP service requires signing to run on Windows
    runs-on: windows-latest
    needs: build-and-lay-out
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.0

    - name: Download payload
      uses: actions/download-artifact@v2
      with:
        name: macos-payload
        path: payload
    
    - name: Zip payload
      shell: pwsh
      run: |
        Compress-Archive -Path payload .\payload.zip
        Remove-Item payload -Recurse
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Install ESRP client
      shell: pwsh
      env:
        AZ_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      run: |
        az storage blob download --file esrp.zip --account-key "$env:AZ_KEY" --account-name gcmesrp --container microsoft-esrp-client --name microsoft.esrpclient.1.2.76.nupkg
        Expand-Archive -Path esrp.zip -DestinationPath .\esrp
    
    - name: Install certificates
      shell: pwsh
      env:
        AZ_VAULT: ${{ secrets.AZURE_VAULT }}
        AUTH_CERT: ${{ secrets.AZURE_VAULT_AUTH_CERT_NAME }}
        REQUEST_SIGNING_CERT: ${{ secrets.AZURE_VAULT_REQUEST_SIGNING_CERT_NAME }}
      run: |
        az keyvault secret download --vault-name "$env:AZ_VAULT" --name "$env:AUTH_CERT" --file out.pfx
        certutil -f -importpfx out.pfx
        Remove-Item out.pfx

        az keyvault secret download --vault-name "$env:AZ_VAULT" --name "$env:REQUEST_SIGNING_CERT" --file out.pfx
        certutil -f -importpfx out.pfx
        Remove-Item out.pfx
    
    - name: Run ESRP client
      shell: pwsh
      env:
        AZURE_AAD_ID: ${{ secrets.AZURE_AAD_ID }}
        AZURE_AAD_ID_TEMP: ${{ secrets.AAD_ID_TEMP }}
      run: |
        python .github\run_esrp_signing.py .\payload.zip "CP-401337-Apple" "MacAppDeveloperSign" --params "Hardening --options=runtime"
    
    - name: Upload signed payload
      uses: actions/upload-artifact@v2
      with:
        name: macos-signed-payload
        path: |
          signed\*